# Generated by Django 4.1.4 on 2023-01-05 14:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('create_date', models.DateField(verbose_name='date created')),
                ('reg_code', models.CharField(max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(7)])),
                ('search_string', models.CharField(blank=True, max_length=500, null=True)),
                ('autofill_string', models.CharField(blank=True, max_length=104, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareholder_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shareholder_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shareholder_company_name', models.CharField(blank=True, max_length=10, null=True)),
                ('shareholder_company_reg_code', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.MinLengthValidator(7)])),
                ('capital', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('id_code', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(12)])),
                ('founder', models.BooleanField()),
                ('physical_person', models.BooleanField()),
                ('autofill_string', models.CharField(blank=True, max_length=104, null=True)),
                ('reg_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proovitoo.header')),
            ],
        ),
    ]
