# Generated by Django 4.1.4 on 2023-01-08 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proovitoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='id_code',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='detail',
            name='shareholder_company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
